// Generated by LiveScript 1.4.0
(function(){
  var main;
  main = function(){
    var i$, ref$, len$, node, par, fs, results$ = [];
    for (i$ = 0, len$ = (ref$ = document.querySelectorAll('.bigtext')).length; i$ < len$; ++i$) {
      node = ref$[i$];
      par = node.parentNode;
      fs = 20;
      for (;;) {
        if (fs > 1000 || node.offsetWidth > par.offsetWidth) {
          break;
        }
        fs += 2;
        node.style.fontSize = fs + 'px';
      }
      fs -= 2;
      node.style.fontSize = fs + 'px';
      node.style.lineHeight = 0.8 * fs + 'px';
      results$.push(node.style.display = 'block');
    }
    return results$;
  };
  main();
}).call(this);
